### ISSUE TITLE
Roadmap for 0.1 

### ISSUE THREAD

**Issue by MarianoGnu** [EasyRPG/Editor#48]
# Main Window:
- [x] Open project.
- [x] Create new project.
- [x] Close project.
- [x] Import project.
- [ ] Create new map.
- [ ] Edit map properties.
- [ ] Copy/paste maps.
- [ ] Delete maps.
- [x] Open maps in independent tabs.
- [x] Launch Game.
- [x] launch game in a specific position (skips title scene).
# Map View:
- [x] Render Maps.
- [x] Render Autotiles correctly.
- [x] Edit upper and lower layers using a pen tool.
- [x] Edit upper and lower layers using a rectangle tool.
- [ ] Edit upper and lower layers using a circle tool.
- [x] Edit upper and lower layers using a fill tool.
- [x] Undo last draw.
## Events
- [x] Show map's event edition window.
- [x] Edit event's page initial conditions and options.
- [x] list event commands in a tree widget.
- [x] Verbalize event commands. (53/123).
- [ ] Edit event commands.
- [ ] Add new event commands.
- [ ] Add new event pages.
- [ ] Copy/paste event pages.
- [ ] Delete event pages.
- [x] Undo last event edition.
# Database
- [ ] Show data in _oldSchool_ tabs (2/17).
- [ ] Show data in  _newStyle_ tables (0/17).
- [x] Save changes when clicking Apply or Ok buttons.
- [x] Split edition tabs in independent widgets.
## Actors
- [x] Fill Actors List.
- [x] Display selected actor's data.
- [x] Render evolution curves.
- [x] Render actor's Face, CharaSet and Battler.
- [x] Modify string values (2/2)
- [x] Modify numeric values (10/10)
- [x] Modify check values (5/5)
- [ ] Modify evolution curves.
- [ ] Modify experience curve.
- [ ] Modify skill learning table.
- [ ] Modify Attribute/States rank asociation.
- [x] Set parametters when **Apply Profession** button is pressed.
## Professions
- [x] Fill Professions List.
- [ ] Display selected profession's data.
- [ ] Render Profession's Battler and curves.
## Vocabulary
- [x] Display data.
- [x] Modify data.
## 14 Remaning Tabs.
- [ ] Fill data.
- [ ] Modify data.
